### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ndastur** [jpriebe/TitanUp#1]
Hi Jason

Looks like a great set of classes. Do you mind confirming the license and if you are okay with forks and reuse etc. I am think of making some of this into alloy widgets.

Thanks

**Comment by jpriebe** [comment]
Apache 2.0.  You can definitely reuse it or respin it.  Sorry for the tremendously long delay in responding -- I am not getting e-mail notifications of these issues, apparently.  :-(
