### ISSUE TITLE
TU.LOGGER

### ISSUE THREAD

**Issue by jmessick9** [jpriebe/TitanUp#2]
Tried to load this getting an error:

[ERROR] :  Script Error Couldn't find module: /TitanUp/Logger for architecture: i386
[ERROR] :  Script Error Module "/TitanUp/TitanUp" failed to leave a valid exports object
[DEBUG] :  Application booted in 53.476036 ms
[ERROR] :  ErrorController is up. ABORTING showing of modal controller

Looks like the Logger js file is missing when I downloaded this. I don't see it anywhere in the files.

**Comment by jmessick9** [comment]
Anyway to get these files?

**Comment by srikpunu** [comment]
Can someone please suggest "How to get Logger file? Pleaseee. It is not compiling.

**Comment by jpriebe** [comment]
Sorry -- please get the latest code; I made a bad push last month.

**Comment by srikpunu** [comment]
Thank you very much. I will try today.

**Comment by jmessick9** [comment]
Thanks!

On Tue, Feb 17, 2015 at 11:14 AM, srikpunu notifications@github.com wrote:

> Thank you very much. I will try today.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jpriebe/TitanUp/issues/2#issuecomment-74731599.

## 

No trees were killed to send this message, but a large number of electrons
were terribly inconvenienced.
