### ISSUE TITLE
setBackground throws NoSuchMethodError

### ISSUE THREAD

**Issue by shopmium** [jpriebe/TitanUp#5]
Hi Jason,

Thanks for your module. Everything is working fine but when I use device with Android versions under the API 16 my app keeps crashing. 

Here is the LogCat:

01-01 05:48:15.930: E/AndroidRuntime(11409): FATAL EXCEPTION: main
01-01 05:48:15.930: E/AndroidRuntime(11409): java.lang.NoSuchMethodError: android.widget.TextView.setBackground
01-01 05:48:15.930: E/AndroidRuntime(11409):  at so.hau.tomas.pager.util.UIUtils.styleTabView(UIUtils.java:54)
01-01 05:48:15.930: E/AndroidRuntime(11409):  at so.hau.tomas.pager.indicator.TabStyleScrolling$TabView.updateStyle(TabStyleScrolling.java:243)

setBackground() was be created only in 16 api,  to solve this error  :
(UIUtils.java) line 54 : 
if ( Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN ) {
    view.setBackground(bgState);
}
else {
   view.setBackgroundDrawable(bgState);
}

Same issue line 118

Can you fix it as soon as possible or is it possible to publish your source code for contributions ?

Thanks

**Comment by shopmium** [comment]
I didn't see duplicated issues : https://github.com/mudderman/ViewPager-Module-Demo/issues/5

**Comment by jpriebe** [comment]
Also, make sure you're using the latest code for the ViewPager module:

http://tomas.hau.so/posts/2013/10/02/viewpager-module-revisited/

It says it's a preview version, but nothing seems to have happened in 18 months.  I hope some day the source for this module will be published on github, but for now, this version seems to be pretty stable.
